export const NavigationString = {
    Register: "Register",
    Login: "Login",
    Home: "Home",
    Drawer: "Drawer",
    Profile: "Profile",
    Dashboard: "Dashboard",
    ChooseRole: "ChooseRole",
    FindDoctor: "FindDoctor",
    FindConcern: "FindConcern",
    DoctorDetails: "DoctorDetails",
    Appointments: "Appointments",
    MyDoctors: "MyPatient",
    ProfileUpdate: "ProfileUpdate",
    UploadPrecription:"UploadPrecription",
    AllAppoinment:"AllAppoinment",
    AllPatients:"AllPatients",
    ForgotPassword:"ForgotPassword",
    PdfViewerScreen: "PdfViewerScreen",
    MobileLogin:"MobileLogin",
    MobileVerify:"MobileVerify",
    AudioCallScreen: "AudioCallScreen",
    VideoCallScreen: "VideoCallScreen",
    TimingSlot: "TimingSlot",
}